/**
 * Upgrade-Path Regression Test
 *
 * Usage: node tests/run-electron-node-test.cjs tests/upgrade-path.test.ts
 *
 * Fresh-install tests (schema-health.test.ts) only ever see a customers
 * table built by *today's* createSchema() — which already includes every
 * column createSchema() has ever grown, since it's a single function
 * describing the current desired shape. They can never catch the class of
 * bug fixed in 9c92409: a column (customers.country_code, then
 * customers.tag_counts) was added straight into createSchema() without a
 * paired ALTER migration for pre-existing installs, so any real install
 * whose customers table was created before those columns existed kept
 * missing them forever — CREATE TABLE IF NOT EXISTS in migration v1 is a
 * no-op once the table already exists. It crashed with
 * "no such column: country_code" the first time migration v23 tried to
 * use it (reported on a v1.9.7 upgrade).
 *
 * This test runs the *real* migration chain against a real database
 * fixture captured from an actual old release (tests/fixtures/upgrade-
 * snapshots/pre-migration-scheme-v1.5.0.db, generated by
 * scripts/generate-upgrade-fixture.ts / see specs/DatabaseMigrations.md) —
 * the only way to reproduce "an install whose table predates a column that
 * now only lives in createSchema()". If a future column gets added to
 * createSchema() without a matching guarded migration, this test fails the
 * same way production did, instead of a user finding out on upgrade.
 */
import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';

const Module = require('module');
const originalLoad = Module._load;
const testDir = fs.mkdtempSync(path.join(os.tmpdir(), 'flo-upgrade-path-'));

const FIXTURE = path.join(__dirname, 'fixtures/upgrade-snapshots/pre-migration-scheme-v1.5.0.db');
const upgradeDbPath = path.join(testDir, 'flo.db');
fs.copyFileSync(FIXTURE, upgradeDbPath);

const FixtureDatabase = require('better-sqlite3');
const fixtureDb = new FixtureDatabase(upgradeDbPath);
const legacyTaxBreakdown = JSON.stringify([{ title: 'Legacy Tax', rate: 5, amount: 5 }]);
const legacyOrder = fixtureDb.prepare(`
  INSERT INTO orders (order_number, subtotal, tax_amount, tax_breakdown, total)
  VALUES ('ORD-LEGACY-TAX', 100, 5, ?, 105)
`).run(legacyTaxBreakdown);
const legacyBill = fixtureDb.prepare(`
  INSERT INTO bills (bill_number, order_id, subtotal, tax_amount, tax_breakdown, total)
  VALUES ('INV-LEGACY-TAX', ?, 100, 5, ?, 105)
`).run(legacyOrder.lastInsertRowid, legacyTaxBreakdown);
fixtureDb.prepare(`UPDATE bills SET payment_details = ? WHERE id = ?`).run(
  JSON.stringify({ method: 'upi', amount: 105, timestamp: '2026-07-01T11:30:00.000Z' }),
  legacyBill.lastInsertRowid,
);
fixtureDb.prepare(`
  INSERT OR REPLACE INTO settings (key, value, updated_at) VALUES
    ('cloud_sync_enabled', '0', '2026-08-01 12:00:00'),
    ('cloud_pending_store_id', 'old-pending-id', '2026-08-01 12:00:00'),
    ('cloud_server_url', 'https://example.test/', '2026-08-01 12:00:00')
`).run();
fixtureDb.prepare(`
  INSERT OR REPLACE INTO settings (key, value, updated_at)
  VALUES ('cloud_orders_enabled', '0', '2026-08-01T12:00:00.000Z')
`).run();
// Pre-v45 era rows written by the old `now()` (ISO-8601 with T/Z/ms). Migration
// v45 must normalize these to the space form so range/order/compare operations
// see one consistent format.
const isoOrder = fixtureDb.prepare(`
  INSERT INTO orders (order_number, subtotal, tax_amount, total, created_at, updated_at, cooking_started_at, ready_at)
  VALUES ('ORD-ISO-TS', 10, 0, 10, '2026-07-01T10:00:00.123Z', '2026-07-01T10:00:00.123Z', '2026-07-01T10:05:00.000Z', '2026-07-01T10:12:00.000Z')
`).run();
fixtureDb.prepare(`
  INSERT INTO bills (bill_number, order_id, subtotal, tax_amount, total, paid_at, created_at, updated_at)
  VALUES ('INV-ISO-TS', ?, 10, 0, 10, '2026-07-01T11:30:00.000Z', '2026-07-01T11:00:00.000Z', '2026-07-01T11:30:00.000Z')
`).run(isoOrder.lastInsertRowid);
// A real, pre-v73 tracked-stock product — none of the fixture's stock
// products happen to have track_inventory=1, so the inventory ledger
// migration (v73)'s opening-balance backfill needs one injected here to be
// exercised meaningfully. See the "opening balance" assertions below.
fixtureDb.prepare(`
  INSERT INTO products (id, category_id, name, price, track_inventory, stock_quantity, is_active, sort_order, created_at, updated_at)
  VALUES ('prod-legacy-stock', NULL, 'Legacy Tracked Widget', 9.99, 1, 42, 1, 0, '2026-07-01T10:00:00.000Z', '2026-07-01T10:00:00.000Z')
`).run();
fixtureDb.close();

const mockApp = {
  isPackaged: true,
  getPath: (_name: string) => testDir,
  getVersion: () => 'test',
};

Module._load = function (request: string, parent: unknown, isMain: boolean) {
  if (request === 'electron') return { app: mockApp };
  return originalLoad.apply(this, arguments as any);
};

function isNativeAbiMismatch(error: any): boolean {
  return error?.code === 'ERR_DLOPEN_FAILED'
    && String(error?.message || '').includes('NODE_MODULE_VERSION');
}

function main() {
  console.log('🧪 FloDesktop Upgrade-Path Regression Test');
  console.log('='.repeat(60));

  const {
    initDatabase, getDatabase, closeDatabase, getCurrentSchemaVersion, buildIdealSchemaDb,
  } = require('../main/db');
  const { runHealthCheck } = require('../main/services/schema-health');

  // ── The real chain, against a real old install, must not throw ──────────
  try {
    initDatabase();
  } catch (error: any) {
    if (isNativeAbiMismatch(error)) {
      console.log('   ⚠ Skipping: better-sqlite3 is not built for this shell Node ABI.');
      process.exit(77);
    }
    throw new Error(`migrating a real old install (v1.5.0 era) crashed: ${error.message}`);
  }
  console.log('   ✓ an old (pre-migration-array) install migrates through to the latest schema without crashing');

  const db = getDatabase();
  // PLEMMO FORK: migration v40 (upstream) flipped this on during upgrade;
  // migration v67 (Plemmo) turns it back off so an upgraded database never
  // starts talking to the upstream vendor's service.
  assert.equal(db.prepare("SELECT value FROM settings WHERE key = 'cloud_sync_enabled'").get().value, '0',
    'PLEMMO v67 leaves cloud sync disabled after upgrading an existing install');
  assert.equal(db.prepare("SELECT COUNT(*) AS count FROM settings WHERE key = 'cloud_pending_store_id'").get().count, 0,
    'pending registration state is removed during upgrade');
  assert.equal(db.prepare("SELECT value FROM settings WHERE key = 'cloud_orders_enabled'").get().value, '0',
    'explicitly edited settings remain unchanged during upgrade');
  assert.equal(db.prepare("SELECT value FROM settings WHERE key = 'taxes_enabled'").get().value, 'false',
    'taxes remain off until the merchant enables them');

  // PLEMMO v73: the inventory ledger's opening-balance backfill against a
  // real legacy tracked-stock product (injected above, since none of the
  // fixture's own products happen to track inventory).
  const openingMovement = db.prepare(`
    SELECT * FROM inventory_movements
    WHERE reference_type = 'opening_stock_migration' AND reference_id = 'prod-legacy-stock'
  `).get() as any;
  assert.ok(!!openingMovement, 'v73 creates an opening movement for a pre-existing tracked-stock product');
  assert.equal(openingMovement.movement_type, 'opening', 'the migration-created movement is typed opening');
  assert.equal(openingMovement.quantity_delta, 42, 'the opening movement carries the exact legacy stock_quantity');
  const openingBalance = db.prepare(`
    SELECT quantity FROM inventory_balances WHERE product_id = 'prod-legacy-stock' AND product_variant_id IS NULL
  `).get() as any;
  assert.equal(openingBalance.quantity, 42, 'the balance table starts at the same legacy quantity');
  assert.ok(db.prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = 'support_ticket_outbox'").get(),
    'support ticket outbox exists after upgrade');
  console.log('   ✓ v40/v41 preserves deliberate settings, flips untouched cloud sync, and creates the support outbox');
  const ideal = buildIdealSchemaDb();
  const latestSchemaVersion = ideal.pragma('user_version', { simple: true }) as number;
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion,
    'migrated old install reaches the same schema version as a fresh install');
  ideal.close();
  assert.equal(
    (db.prepare("SELECT value FROM settings WHERE key = 'split_checks_enabled'").get() as { value: string }).value,
    'false',
    'existing stores receive the opt-in split-check default during upgrade',
  );
  console.log('   ✓ existing stores receive split checks disabled by default');
  assert.equal(
    (db.prepare("SELECT value FROM settings WHERE key = 'bill_template'").get() as { value: string }).value,
    'classic',
    'existing stores receive the classic bill template during upgrade',
  );
  assert.equal(
    (db.prepare("SELECT value FROM settings WHERE key = 'bill_footer_message'").get() as { value: string }).value,
    '',
    'existing stores receive an empty bill footer during upgrade',
  );
  console.log('   ✓ existing stores receive bill template defaults without requiring a first save');

  const migratedUpi = db.prepare(`
    SELECT pm.id, pm.name, b.payment_details
    FROM bills b
    JOIN payment_methods pm ON pm.id = json_extract(b.payment_details, '$.payment_method_id')
    WHERE b.bill_number = 'INV-LEGACY-TAX'
  `).get() as { id: number; name: string; payment_details: string };
  assert.equal(migratedUpi.name, 'UPI', 'historical UPI is preserved as a custom method on upgrade');
  assert.equal(JSON.parse(migratedUpi.payment_details).method, 'UPI', 'historical UPI payment is linked to the preserved method');
  console.log('   ✓ legacy UPI payments are preserved without seeding UPI on fresh installs');

  // ── Migration v45: legacy ISO timestamps are normalized to the space form ─
  const isoOrderRow = db.prepare(
    `SELECT created_at, updated_at, cooking_started_at, ready_at FROM orders WHERE order_number = 'ORD-ISO-TS'`
  ).get() as { created_at: string; updated_at: string; cooking_started_at: string; ready_at: string };
  assert.deepEqual(
    [isoOrderRow.created_at, isoOrderRow.updated_at, isoOrderRow.cooking_started_at, isoOrderRow.ready_at],
    ['2026-07-01 10:00:00', '2026-07-01 10:00:00', '2026-07-01 10:05:00', '2026-07-01 10:12:00'],
    'v45 normalizes legacy ISO order timestamps to the space form (second precision)',
  );
  const isoBillRow = db.prepare(
    `SELECT created_at, updated_at, paid_at FROM bills WHERE bill_number = 'INV-ISO-TS'`
  ).get() as { created_at: string; updated_at: string; paid_at: string };
  assert.deepEqual(
    [isoBillRow.created_at, isoBillRow.updated_at, isoBillRow.paid_at],
    ['2026-07-01 11:00:00', '2026-07-01 11:30:00', '2026-07-01 11:30:00'],
    'v45 normalizes legacy ISO bill timestamps to the space form',
  );
  assert.ok(
    db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'index' AND name = 'idx_bills_paid_at'`).get(),
    'v45 creates idx_bills_paid_at for the payment-method breakdown scan',
  );
  console.log('   ✓ legacy ISO timestamps are normalized to the space form (v45)');

  const customerColumns = db.prepare(`PRAGMA table_info(customers)`).all().map((c: any) => c.name);
  assert.ok(customerColumns.includes('country_code'), 'customers.country_code exists after migrating an old install');
  assert.ok(customerColumns.includes('tag_counts'), 'customers.tag_counts exists after migrating an old install');
  console.log('   ✓ customers.country_code and customers.tag_counts are present (the 9c92409 regression)');

  const requiredTaxTables = [
    'country_packs',
    'country_pack_versions',
    'tax_categories',
    'tax_rules',
    'tax_overrides',
    'tax_config_audit',
  ];
  for (const table of requiredTaxTables) {
    assert.ok(
      db.prepare(`SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?`).get(table),
      `${table} exists after upgrading an old install`,
    );
  }
  const expectedTaxColumns: Record<string, string[]> = {
    products: ['tax_category_id', 'tax_behavior', 'tax_type', 'tax_rate'],
    addons: ['tax_category_id', 'tax_behavior', 'inherit_parent_tax_category'],
    orders: [
      'tax_snapshot',
      'packaging_tax_category_id',
      'delivery_tax_category_id',
      'service_charge_tax_category_id',
    ],
    order_items: ['tax_snapshot'],
    bills: ['tax_snapshot'],
  };
  for (const [table, expected] of Object.entries(expectedTaxColumns)) {
    const columns = db.prepare(`PRAGMA table_info(${table})`).all().map((column: any) => column.name);
    for (const column of expected) {
      assert.ok(columns.includes(column), `${table}.${column} exists after upgrading an old install`);
    }
  }
  console.log('   ✓ old installs receive every Phase 1 tax table and guarded additive column');
  assert.equal(
    (db.prepare('SELECT COUNT(*) AS count FROM country_packs').get() as { count: number }).count,
    1,
    'old installs register only the generic tax pack during upgrade',
  );
  assert.equal(
    (db.prepare('SELECT COUNT(*) AS count FROM country_pack_versions').get() as { count: number }).count,
    1,
    'old installs register only the generic tax pack version during upgrade',
  );
  console.log('   ✓ old installs receive generic tax behavior without replacing legacy tax data');

  // 10 from the fixture + 1 injected above (prod-legacy-stock, for the v73 opening-balance assertions).
  assert.equal((db.prepare('SELECT COUNT(*) AS count FROM products').get() as any).count, 11);
  // A product originating in this pre-tax-engine fixture can still carry the
  // old tax_type/tax_rate columns after Phase 1, but those columns are not
  // authoritative for new calculations — tax is opt-in through an explicitly
  // resolved category only. An upgraded install must not silently start
  // charging tax again based on stale legacy columns.
  const legacyProduct = db.prepare('SELECT * FROM products LIMIT 1').get() as any;
  db.prepare(`UPDATE products SET tax_category_id = NULL, tax_type = 'exclusive', tax_rate = 18 WHERE id = ?`)
    .run(legacyProduct.id);
  const { calculateItemTax } = require('../main/services/tax');
  const legacyTax = calculateItemTax(
    // taxes_enabled: true here, deliberately, even though this install's
    // actual setting is 'false' (asserted above) — the point of this
    // assertion is that an unresolved category charges no tax on its own
    // merits, not that the global switch happens to also be off.
    { country: 'IN', business_type: 'restaurant', state_code: 'KA', taxes_enabled: true },
    db.prepare('SELECT * FROM products WHERE id = ?').get(legacyProduct.id),
    100,
    null,
  );
  assert.equal(legacyTax.tax_amount, 0, 'an upgraded product with no resolved tax category charges no tax');
  assert.deepEqual(legacyTax.tax_breakdown, []);
  console.log('   ✓ an upgraded product with stale legacy tax_type/tax_rate charges no tax until categorized');
  const preservedOrder = db.prepare(`
    SELECT tax_amount, tax_breakdown, tax_snapshot FROM orders WHERE order_number = 'ORD-LEGACY-TAX'
  `).get() as any;
  const preservedBill = db.prepare(`
    SELECT tax_amount, tax_breakdown, tax_snapshot FROM bills WHERE bill_number = 'INV-LEGACY-TAX'
  `).get() as any;
  assert.deepEqual(
    { tax_amount: preservedOrder.tax_amount, tax_breakdown: preservedOrder.tax_breakdown },
    { tax_amount: 5, tax_breakdown: legacyTaxBreakdown },
  );
  assert.deepEqual(
    { tax_amount: preservedBill.tax_amount, tax_breakdown: preservedBill.tax_breakdown },
    { tax_amount: 5, tax_breakdown: legacyTaxBreakdown },
  );
  assert.equal(preservedOrder.tax_snapshot, null);
  assert.equal(preservedBill.tax_snapshot, null);
  console.log('   ✓ existing products, orders, bills, and legacy tax breakdowns are preserved');

  // PLEMMO v69 — every pre-existing transactional row must come out of the
  // upgrade carrying a collision-safe uid. This is the assertion that proves
  // the backfill works against a REAL legacy database rather than only on a
  // fresh one, which is where a backfill normally breaks.
  const ULID_RE = /^[0-9A-HJKMNP-TV-Z]{26}$/;
  for (const table of ['orders', 'order_items', 'bills'] as const) {
    const total = (db.prepare(`SELECT COUNT(*) AS c FROM ${table}`).get() as { c: number }).c;
    const missing = (db.prepare(`SELECT COUNT(*) AS c FROM ${table} WHERE uid IS NULL`).get() as { c: number }).c;
    assert.equal(missing, 0, `every legacy ${table} row was backfilled with a uid (${total} rows)`);
    const distinct = (db.prepare(`SELECT COUNT(DISTINCT uid) AS c FROM ${table}`).get() as { c: number }).c;
    assert.equal(distinct, total, `every legacy ${table} uid is distinct`);
    const rows = db.prepare(`SELECT uid FROM ${table}`).all() as { uid: string }[];
    for (const row of rows) {
      assert.ok(ULID_RE.test(row.uid), `${table}.uid ${row.uid} is a well-formed ULID`);
    }
  }
  // Backfill seeds each ULID's timestamp from the row's own created_at, so a
  // lexicographic sort on uid must reproduce creation order rather than
  // clustering every legacy row at migration time.
  const ordered = db.prepare(`SELECT uid, created_at FROM orders ORDER BY created_at ASC, id ASC`).all() as { uid: string }[];
  const byUid = ordered.map((r) => r.uid).slice().sort();
  assert.deepEqual(ordered.map((r) => r.uid), byUid,
    'backfilled uids sort in the same order as created_at');
  console.log('   ✓ legacy orders/order_items/bills are backfilled with unique, time-ordered ULIDs (v69)');

  // PLEMMO v68 — an upgraded install gets the same single-tenant hierarchy a
  // fresh one does, seeded from its existing business name.
  const upgradedOrg = db.prepare('SELECT * FROM organizations').all() as any[];
  assert.equal(upgradedOrg.length, 1, 'an upgraded install has exactly one organization');
  const upgradedDevice = db.prepare('SELECT * FROM devices').all() as any[];
  assert.equal(upgradedDevice.length, 1, 'an upgraded install has exactly one device');
  assert.equal(
    (db.prepare("SELECT value FROM settings WHERE key = 'plemmo_device_id'").get() as any)?.value,
    upgradedDevice[0].id,
    'the device pointer matches the seeded device row after upgrade',
  );
  assert.equal((db.prepare('PRAGMA foreign_key_check').all() as any[]).length, 0,
    'the seeded hierarchy introduces no FK violations into a real legacy database');
  console.log('   ✓ upgraded installs receive the Plemmo org/location/register/device hierarchy (v68)');

  // ── The migrated old install must match the ideal (fresh) schema exactly ─
  const report = runHealthCheck();
  assert.equal(report.findings.length, 0,
    `a migrated old install should match a fresh install's schema exactly, found: ${JSON.stringify(report.findings)}`);
  console.log('   ✓ runHealthCheck() reports zero drift between the migrated old install and a fresh install');

  // ── The columns must actually be usable, not just present ───────────────
  const customerId = db.prepare(`SELECT id FROM customers LIMIT 1`).get() as { id: string } | undefined;
  if (customerId) {
    db.prepare(`UPDATE customers SET country_code = '+1', tag_counts = '{}' WHERE id = ?`).run(customerId.id);
    const row = db.prepare(`SELECT country_code, tag_counts FROM customers WHERE id = ?`).get(customerId.id) as any;
    assert.equal(row.country_code, '+1');
    assert.equal(row.tag_counts, '{}');
    console.log('   ✓ the backfilled columns are readable and writable');
  }

  const existingCountryPack = require('./fixtures/synthetic-dual-rate-pack.json');
  const preservedVersionId = `${existingCountryPack.id}@existing-active`;
  const preservedAt = '2026-07-30T00:00:00.000Z';
  db.prepare(`
    INSERT INTO country_packs (
      id, publisher, country, jurisdiction, active_version_id, status, created_at, updated_at
    ) VALUES (?, ?, ?, ?, ?, 'active', ?, ?)
  `).run(
    existingCountryPack.id,
    existingCountryPack.publisher,
    existingCountryPack.country,
    existingCountryPack.jurisdiction,
    preservedVersionId,
    preservedAt,
    preservedAt,
  );
  db.prepare(`
    INSERT INTO country_pack_versions (
      id, pack_id, version, schema_version, manifest_json, pack_json, digest, signature,
      effective_from, effective_to, min_flo_version, published_at, status, created_at
    ) VALUES (?, ?, ?, ?, '{}', ?, ?, NULL, ?, NULL, ?, ?, 'active', ?)
  `).run(
    preservedVersionId,
    existingCountryPack.id,
    'existing-active',
    existingCountryPack.schemaVersion,
    JSON.stringify(existingCountryPack),
    'preserved-existing-version',
    existingCountryPack.effectiveFrom,
    existingCountryPack.minFloVersion,
    existingCountryPack.publishedAt,
    preservedAt,
  );
  db.prepare("UPDATE settings SET value = 'true' WHERE key = 'split_checks_enabled'").run();
  db.pragma('user_version = 37');
  closeDatabase();
  initDatabase();
  assert.equal(getCurrentSchemaVersion(), latestSchemaVersion);
  assert.equal(runHealthCheck().findings.length, 0);
  const preservedPack = getDatabase().prepare(`
    SELECT active_version_id, status FROM country_packs WHERE id = ?
  `).get(existingCountryPack.id) as { active_version_id: string; status: string };
  assert.deepEqual(
    preservedPack,
    { active_version_id: preservedVersionId, status: 'active' },
    'an already-active country pack survives the changed bundle migration untouched',
  );
  assert.ok(
    getDatabase().prepare('SELECT 1 FROM country_pack_versions WHERE id = ?').get(preservedVersionId),
    'the previously installed active pack version is preserved',
  );
  assert.equal(
    (getDatabase().prepare("SELECT value FROM settings WHERE key = 'split_checks_enabled'").get() as { value: string }).value,
    'true',
    'v60 preserves an existing split-check choice',
  );
  getDatabase().prepare(`UPDATE settings SET value = 'false' WHERE key = 'diagnostics_consent'`).run();
  getDatabase().pragma('user_version = 46');
  closeDatabase();
  initDatabase();
  const diagnosticsSetting = getDatabase().prepare(
    `SELECT value FROM settings WHERE key = 'diagnostics_consent'`,
  ).get() as { value: string };
  assert.equal(diagnosticsSetting.value, 'false', 'v47 preserves an existing diagnostics opt-out');
  console.log('   ✓ reopening is idempotent and preserves an already-active country pack');
  closeDatabase();

  console.log('='.repeat(60));
  console.log('✅ Upgrade-path regression test passed');
}

main();
